---
# tasks file for install-terraform
- name: Update all packages to their latest version
  apt:
    update_cache: yes
    force_apt_get: yes
- name: INSTALLING REQUIRED PACKAGES FOR ANISBLE
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - gnupg
    - software-properties-common
    - curl
- name: Add HashiCorp GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
- name: Add HashiCorp repository
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com jammy main"
    state: present
- name: Update all packages to their latest version
  apt:
    update_cache: yes
    force_apt_get: yes
- name: Install containerd.io
  apt:
    pkg:
    - terraform
